# напиши тут код для другого екрана програми
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QLabel, QVBoxLayout, QLineEdit, QHBoxLayout
from instr import *

app1 = QApplication([])
main_win1 = QWidget()
main_win1.setWindowTitle(txt_title)
main_win1.move(900, 70)
main_win1.resize(1000, 600)
layout1 = QVBoxLayout()
layout2 = QVBoxLayout()
main_layout = QHBoxLayout()

text1 = QLabel(txt_name)
PIB_input = QLineEdit(txt_hintname)
text2 = QLabel(txt_age)
age_input = QLineEdit(txt_hintage)
text3 = QLabel(txt_test1)
first_button = QPushButton(txt_starttest1)
first_pulse_input = QLineEdit(txt_hinttest1)
text4 = QLabel(txt_test2)
second_button = QPushButton(txt_starttest2)
text5 = QLabel(txt_test3)
final_button = QPushButton(txt_starttest3)
second_pulse_input = QLineEdit(txt_hinttest2)
final_pulse_input = QLineEdit(txt_hinttest3)
next_button = QPushButton(txt_sendresults)
timer = QLabel(txt_timer)

layout1.addWidget(text1, alignment=Qt.AlignLeft)
layout1.addWidget(PIB_input, alignment=Qt.AlignLeft)
layout1.addWidget(text2, alignment=Qt.AlignLeft)
layout1.addWidget(age_input, alignment=Qt.AlignLeft)
layout1.addWidget(text3, alignment=Qt.AlignLeft)
layout1.addWidget(first_button, alignment=Qt.AlignLeft)
layout1.addWidget(first_pulse_input, alignment=Qt.AlignLeft)
layout1.addWidget(text4, alignment=Qt.AlignLeft)
layout1.addWidget(second_button, alignment=Qt.AlignLeft)
layout1.addWidget(text5, alignment=Qt.AlignLeft)
layout1.addWidget(first_button, alignment=Qt.AlignLeft)
layout1.addWidget(second_pulse_input, alignment=Qt.AlignLeft)
layout1.addWidget(final_pulse_input, alignment=Qt.AlignLeft)
layout1.addWidget(next_button, alignment=Qt.AlignCenter)
layout2.addWidget(timer)
main_layout.addLayout(layout1)
main_layout.addLayout(layout2)
main_win1.setLayout(main_layout)

main_win1.show()
app1.exec_()
